export const categoryNames = [
  {
    name: "latest",
    icon: "/icons/latest.png",
    route: "/articles/categories/latest",
  },
  {
    name: "ageing well",
    icon: "/icons/ageing.png",
    route: "/articles/categories/ageing-well",
  },
  {
    name: "health screening",
    icon: "/icons/screening.png",
    route: "/articles/categories/health-screening",
  },
  {
    name: "men's health",
    icon: "/icons/male.png",
    route: "/articles/categories/mens-health",
  },
  {
    name: "neuro",
    icon: "/icons/neuro.png",
    route: "/articles/categories/neuro",
  },
  {
    name: "vascular",
    icon: "/icons/vascular.png",
    route: "/articles/categories/vascular",
  },
  {
    name: "women's health",
    icon: "/icons/female.png",
    route: "/articles/categories/womens-health",
  },
  {
    name: "all",
    icon: "/icons/view-all.png",
    route: "/articles",
  },
];

export const categories = {
  neuro: [
    "ADAS-Cog",
    "CST",
    "DBS",
    "ICH",
    "MMSE",
    "SAH",
    "TIA",
    "TTH",
    "ageing",
    "alzheimer's disease",
    "angiogram",
    "angiography",
    "angioplasty",
    "atherectomy",
    "brain",
    "cholinesterase inhibitors",
    "cluster",
    "dementia",
    "dopamine agonist",
    "dopamine",
    "embolic",
    "endarterectomy",
    "headache",
    "hemorrhagic",
    "hemorrhagic",
    "ischemic",
    "levodopa",
    "memantine",
    "migraine",
    "neuro",
    "palliative care",
    "parkinson's disease",
    "sinus",
    "spinal tap",
    "stent",
    "stroke",
    "tension",
    "thrombectomy",
    "thrombolysis",
    "thrombolytic",
    "thrombosis",
    "thrombotic",
    "vascular dementia",
  ],
  "womens-health": [
    "IUD",
    "PCOS",
    "PID",
    "abstinence",
    "birth control pills",
    "birth control ring",
    "contraception",
    "contraceptive",
    "diaphragm cap",
    "endometriosis",
    "femidom",
    "fibroids",
    "hormones",
    "menses",
    "menstrual cycle",
    "menstruation",
    "oral contraceptives",
    "patch",
    "pregnancy",
    "progestin",
    "tubal ligation",
    "women's health",
  ],
  vascular: [
    "DVT",
    "Virchow's triad",
    "anticoagulant",
    "artery",
    "blood clot",
    "blood pressure",
    "blood vessel",
    "capillary",
    "cardiovascular",
    "cholesterol",
    "diet",
    "embolism",
    "thrombectomy",
    "thrombolysis",
    "thrombolytic",
    "thrombosis",
    "vascular disease",
    "vascular",
    "vein",
  ],
  "health-screening": [
    "HDL",
    "LDL",
    "blood glucose",
    "blood pressure",
    "blood sugar level",
    "cancer",
    "chronic disease",
    "diabetes",
    "ezetimibe",
    "health screening",
    "high blood pressure",
    "high cholesterol",
    "hypertension",
    "insulin",
    "lifestyle change",
    "oral medication",
    "plaque",
    "pre-diabetes",
    "saturated fat",
    "statin",
    "sudden death",
    "type 1 diabetes",
    "type 2 diabetes",
    "unsaturated fat",
  ],
  "ageing-well": [
    "DEXA",
    "MCI",
    "ageing well",
    "biphosphonate",
    "bone",
    "caregiver",
    "cognitive decline",
    "dementia",
    "denosumab",
    "depression",
    "elderly",
    "exercise",
    "hormone therapy",
    "lifting weights",
    "mental health",
    "osteoporosis",
    "psychotherapy",
    "screening",
    "therapy",
  ],
  "mens-health": [
    "BPH",
    "TRT",
    "TUMT",
    "TUNA",
    "TURP",
    "UTI",
    "alpha blocker",
    "alpostradil",
    "aromatase inhibitors",
    "benign prostate hyperplasia",
    "cialis",
    "condoms",
    "dopamine",
    "edging",
    "ejaculation",
    "erectile dysfunction",
    "erection",
    "hypogonadism",
    "kegel",
    "libido",
    "men's health",
    "penile implant",
    "penile vascular surgery",
    "premature ejaculation",
    "prostate cancer",
    "prostate",
    "prostatectomy",
    "prostatitis",
    "rezum",
    "semen",
    "sex therapy",
    "testosterone",
    "therapy",
    "viagra",
  ],

  all: [
    "neuro",
    "women's health",
    "vascular",
    "health screening",
    "ageing well",
    "men's health",
  ],
};
